///////////////////////////////////////////////////////////
//  EnergyConsumer.cs
//  Implementation of the Class EnergyConsumer
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:43 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


using TC57CIM.IEC61970.Core;
using TC57CIM.IEC61970.Wires;
using FTN.Common;
using System.Runtime.Serialization;

namespace TC57CIM.IEC61970.Wires {
    /// <summary>
    /// Generic user of energy - a  point of consumption on the power system model.
    /// </summary>

    [DataContract]
    public class EnergyConsumer : ConductingEquipment {

        private float pMax;
        private float qMax;
        private ConsumerType type;
        private float validRangePercent;
        private float invalidRangePercent;

        public EnergyConsumer()
        {

        }

        public EnergyConsumer(long globalId) : base(globalId)
        {
        }

        [DataMember]
        public float ValidRangePercent
        {
            get
            {
                return validRangePercent;
            }

            set
            {
                validRangePercent = value;
            }
        }

        [DataMember]
        public float InvalidRangePercent
        {
            get
            {
                return invalidRangePercent;
            }

            set
            {
                invalidRangePercent = value;
            }
        }

        [DataMember]
        public float PMax
        {
            get { return pMax; }
            set { pMax = value; }
        }

        [DataMember]
        public float QMax
        {
            get { return qMax; }
            set { qMax = value; }
        }

        [DataMember]
        public ConsumerType Type
        {
            get { return type; }
            set { type = value; }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if (base.Equals(obj))
            {
                EnergyConsumer x = (EnergyConsumer)obj;
                return (x.pMax == this.pMax && x.qMax == this.qMax && x.type == this.type && x.validRangePercent == this.validRangePercent &&
                        x.invalidRangePercent == this.invalidRangePercent);
            }
            else
            {
                return false;
            }
        }

        public override string ToString()
        {
            return this.Mrid + "\n" + this.Name;
        }

        #region IAccess implementation

        public override bool HasProperty(ModelCode t)
        {
            switch (t)
            {
                case ModelCode.ENERGYCONS_PMAX:
                case ModelCode.ENERGYCONS_QMAX:
                case ModelCode.ENERGYCONS_TYPE:
                case ModelCode.ENERGYCONS_VALIDRANGEPERCENT:
                case ModelCode.ENERGYCONS_INVALIDRANGEPERCENT:
                    return true;

                default:
                    return base.HasProperty(t);
            }
        }

        public override void GetProperty(Property property)
        {
            switch (property.Id)
            {
                case ModelCode.ENERGYCONS_PMAX:
                    property.SetValue(pMax);
                    break;
                case ModelCode.ENERGYCONS_QMAX:
                    property.SetValue(qMax);
                    break;
                case ModelCode.ENERGYCONS_TYPE:
                    property.SetValue((int)type);
                    break;
                case ModelCode.ENERGYCONS_VALIDRANGEPERCENT:
                    property.SetValue(validRangePercent);
                    break;
                case ModelCode.ENERGYCONS_INVALIDRANGEPERCENT:
                    property.SetValue(invalidRangePercent);
                    break;
                default:
                    base.GetProperty(property);
                    break;
            }
        }

        public override void SetProperty(Property property)
        {
            switch (property.Id)
            {
                case ModelCode.ENERGYCONS_PMAX:
                    pMax = property.AsFloat();
                    break;
                case ModelCode.ENERGYCONS_QMAX:
                    qMax = property.AsFloat();
                    break;
                case ModelCode.ENERGYCONS_TYPE:
                    type = (ConsumerType)property.AsInt();
                    break;
                case ModelCode.ENERGYCONS_VALIDRANGEPERCENT:
                    validRangePercent = property.AsFloat();
                    break;
                case ModelCode.ENERGYCONS_INVALIDRANGEPERCENT:
                    invalidRangePercent = property.AsFloat();
                    break;
                default:
                    base.SetProperty(property);
                    break;
            }
        }

        #endregion IAccess implementation

        public void RD2Class(ResourceDescription rd)
        {
            foreach (Property p in rd.Properties)
            {
                if (p.Id == ModelCode.PSR_MEASUREMENTS)
                {
                    foreach (long l in p.PropertyValue.LongValues)
                    {
                        this.AddReference(ModelCode.MEASUREMENT_PSR, l);
                    }
                }
                else
                {
                    SetProperty(p);
                }
            }
        }

        public EnergyConsumer DeepCopy()
        {
            EnergyConsumer consumerCopy = new EnergyConsumer();

            consumerCopy.GlobalId = this.GlobalId;
            consumerCopy.Mrid = this.Mrid;
            consumerCopy.Name = this.Name;
            consumerCopy.BaseVoltage = this.BaseVoltage;
            consumerCopy.EqContainer = this.EqContainer;
            consumerCopy.Measurements = this.Measurements;
            consumerCopy.PMax = this.PMax;
            consumerCopy.QMax = this.QMax;
            consumerCopy.ValidRangePercent = this.ValidRangePercent;
            consumerCopy.InvalidRangePercent = this.InvalidRangePercent;
            consumerCopy.Type = this.Type;

            return consumerCopy;
        }

    }//end EnergyConsumer

}//end namespace Wires