///////////////////////////////////////////////////////////
//  EnergyConsumer.cs
//  Implementation of the Class EnergyConsumer
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:43 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Domain;
using TC57CIM.IEC61970.Core;
using TC57CIM.IEC61970.LoadModel;
using TC57CIM.IEC61970.Wires;
namespace TC57CIM.IEC61970.Wires {
	/// <summary>
	/// Generic user of energy - a  point of consumption on the power system model.
	/// </summary>
	public class EnergyConsumer : ConductingEquipment {

		/// <summary>
		/// Active power of the load that is a fixed quantity. Load sign convention is used,
		/// i.e. positive sign means flow out from a node.
		/// </summary>
		public TC57CIM.IEC61970.Domain.ActivePower pfixed;
		/// <summary>
		/// Reactive power of the load that is a fixed quantity. Load sign convention is
		/// used, i.e. positive sign means flow out from a node.
		/// </summary>
		public TC57CIM.IEC61970.Domain.ReactivePower qfixed;
		/// <summary>
		/// The load response characteristic of this load.  If missing, this load is
		/// assumed to be constant power.
		/// </summary>
		public TC57CIM.IEC61970.LoadModel.LoadResponseCharacteristic LoadResponse;
		/// <summary>
		/// The individual phase models for this energy consumer.
		/// </summary>
		public TC57CIM.IEC61970.Wires.EnergyConsumerPhase EnergyConsumerPhase;

		public EnergyConsumer(){

		}

		~EnergyConsumer(){

		}

	}//end EnergyConsumer

}//end namespace Wires