///////////////////////////////////////////////////////////
//  PowerTransformerEnd.cs
//  Implementation of the Class PowerTransformerEnd
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:06 PM
//  Original author: Batinic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Wires;
namespace TC57CIM.IEC61970.Wires {
	/// <summary>
	/// A PowerTransformerEnd is associated with each Terminal of a PowerTransformer.
	/// The impdedance values r, r0, x, and x0 of a PowerTransformerEnd represents a
	/// star equivalent as follows
	/// 1) for a two Terminal PowerTransformer the high voltage PowerTransformerEnd has
	/// non zero values on r, r0, x, and x0 while the low voltage PowerTransformerEnd
	/// has zero values for r, r0, x, and x0.
	/// 2) for a three Terminal PowerTransformer the three PowerTransformerEnds
	/// represents a star equivalent with each leg in the star represented by r, r0, x,
	/// and x0 values.
	/// 3) for a PowerTransformer with more than three Terminals the
	/// PowerTransformerEnd impedance values cannot be used. Instead use the
	/// TransformerMeshImpedance or split the transformer into multiple
	/// PowerTransformers.
	/// </summary>
	public class PowerTransformerEnd : TransformerEnd {

		public PowerTransformerEnd(){

		}

		~PowerTransformerEnd(){

		}

	}//end PowerTransformerEnd

}//end namespace Wires