///////////////////////////////////////////////////////////
//  PowerTransformer.cs
//  Implementation of the Class PowerTransformer
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:03 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
using TC57CIM.IEC61970.Wires;
namespace TC57CIM.IEC61970.Wires {
	/// <summary>
	/// An electrical device consisting of  two or more coupled windings, with or
	/// without a magnetic core, for introducing mutual coupling between electric
	/// circuits. Transformers can be used to control voltage and phase shift (active
	/// power flow).
	/// A power transformer may be composed of separate transformer tanks that need not
	/// be identical.
	/// A power transformer can be modelled with or without tanks and is intended for
	/// use in both balanced and unbalanced representations.   A power transformer
	/// typically has two terminals, but may have one (grounding), three or more
	/// terminals.
	/// </summary>
	public class PowerTransformer : ConductingEquipment {

		/// <summary>
		/// The ends of this power transformer.
		/// </summary>
		public TC57CIM.IEC61970.Wires.PowerTransformerEnd PowerTransformerEnd;

		public PowerTransformer(){

		}

		~PowerTransformer(){

		}

	}//end PowerTransformer

}//end namespace Wires