///////////////////////////////////////////////////////////
//  TransformerEnd.cs
//  Implementation of the Class TransformerEnd
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:05 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Wires;
using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Wires {
	/// <summary>
	/// A conducting connection point of a power transformer. It corresponds to a
	/// physical transformer winding terminal.  In earlier CIM versions, the
	/// TransformerWinding class served a similar purpose, but this class is more
	/// flexible because it associates to terminal but is not a specialization of
	/// ConductingEquipment.
	/// </summary>
	public class TransformerEnd : IdentifiedObject {

		/// <summary>
		/// Ratio tap changer associated with this transformer end.
		/// </summary>
		public TC57CIM.IEC61970.Wires.RatioTapChanger RatioTapChanger;
		/// <summary>
		/// Phase tap changer associated with this transformer end.
		/// </summary>
		public TC57CIM.IEC61970.Wires.PhaseTapChanger PhaseTapChanger;
		/// <summary>
		/// (accurate for 2- or 3-winding transformers only) Pi-model impedances of this
		/// transformer end. By convention, for a two winding transformer, the full values
		/// of the transformer should be entered on the high voltage end (endNumber=1).
		/// </summary>
		public TC57CIM.IEC61970.Wires.TransformerStarImpedance StarImpedance;
		/// <summary>
		/// Terminal of the power transformer to which this transformer end belongs.
		/// </summary>
		public TC57CIM.IEC61970.Core.Terminal Terminal;
		/// <summary>
		/// Base voltage of the transformer end.  This is essential for PU calculation.
		/// </summary>
		public TC57CIM.IEC61970.Core.BaseVoltage BaseVoltage;

		public TransformerEnd(){

		}

		~TransformerEnd(){

		}

	}//end TransformerEnd

}//end namespace Wires