///////////////////////////////////////////////////////////
//  Analog.cs
//  Implementation of the Class Analog
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:00 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using TC57CIM.IEC61970.Meas;
using FTN.Common;
using System.Runtime.Serialization;

namespace TC57CIM.IEC61970.Meas
{
    /// <summary>
    /// Analog represents an analog Measurement.
    /// </summary>
    [DataContract]
    [Serializable]
    public class Analog : Measurement
    {
        public Analog()
        {

        }

        public Analog(long globalId)
            : base(globalId)
        {
        }
        
        public override bool Equals(object obj)
        {
            if (base.Equals(obj))
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #region IAccess implementation

        public override bool HasProperty(ModelCode t)
        {
            switch (t)
            {
                default:
                    return base.HasProperty(t);

            }
        }

        public override void GetProperty(Property property)
        {
            switch (property.Id)
            {
                default:
                    base.GetProperty(property);
                    break;
            }
        }

        public override void SetProperty(Property property)
        {
            switch (property.Id)
            {  
                default:
                    base.SetProperty(property);
                    break;
            }
        }

        #endregion IAccess implementation

        public void RD2Class(ResourceDescription rd)
        {
            foreach (Property p in rd.Properties)
            {
                SetProperty(p);
            }
        }

        public Analog DeepCopy()
        {
            Analog analogCopy = new Analog();

            analogCopy.GlobalId = this.GlobalId;
            analogCopy.Mrid = this.Mrid;
            analogCopy.Name = this.Name;
            analogCopy.UnitSymbol = this.UnitSymbol;
            analogCopy.SignalDirection = this.SignalDirection;
            analogCopy.PowerSystemResourceRef = this.PowerSystemResourceRef;

            return analogCopy;
        }


    }//end Analog

}//end namespace Meas