///////////////////////////////////////////////////////////
//  Analog.cs
//  Implementation of the Class Analog
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:00 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using TC57CIM.IEC61970.Meas;
namespace TC57CIM.IEC61970.Meas {
	/// <summary>
	/// Analog represents an analog Measurement.
	/// </summary>
	public class Analog : Measurement {

		/// <summary>
		/// Normal value range maximum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public float maxValue;
		/// <summary>
		/// Normal value range minimum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public float minValue;
		/// <summary>
		/// Normal measurement value, e.g., used for percentage calculations.
		/// </summary>
		public float normalValue;

		public Analog(){

		}

		~Analog(){

		}

	}//end Analog

}//end namespace Meas