///////////////////////////////////////////////////////////
//  Discrete.cs
//  Implementation of the Class Discrete
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:09 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Domain;
using TC57CIM.IEC61970.Meas;
namespace TC57CIM.IEC61970.Meas {
	/// <summary>
	/// Discrete represents a discrete Measurement, i.e. a Measurement reprsenting
	/// discrete values, e.g. a Breaker position.
	/// </summary>
	public class Discrete : Measurement {

		/// <summary>
		/// Normal value range maximum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public TC57CIM.IEC61970.Domain.Integer maxValue;
		/// <summary>
		/// Normal value range minimum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public TC57CIM.IEC61970.Domain.Integer minValue;
		/// <summary>
		/// Normal measurement value, e.g., used for percentage calculations.
		/// </summary>
		public TC57CIM.IEC61970.Domain.Integer normalValue;
		/// <summary>
		/// The Control variable associated with the Measurement.
		/// </summary>
		public TC57CIM.IEC61970.Meas.Command Command;
		/// <summary>
		/// The values connected to this measurement.
		/// </summary>
		public TC57CIM.IEC61970.Meas.DiscreteValue DiscreteValues;

		public Discrete(){

		}

		~Discrete(){

		}

	}//end Discrete

}//end namespace Meas