///////////////////////////////////////////////////////////
//  BaseVoltage.cs
//  Implementation of the Class BaseVoltage
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:11 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Domain;
using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// Defines a system base voltage which is referenced.
	/// </summary>
	public class BaseVoltage : IdentifiedObject {

		/// <summary>
		/// The power system resource's base voltage.
		/// </summary>
		public TC57CIM.IEC61970.Domain.Voltage nominalVoltage;
		/// <summary>
		/// All conducting equipment with this base voltage.  Use only when there is no
		/// voltage level container used and only one base voltage applies.  For example,
		/// not used for transformers.
		/// </summary>
		public TC57CIM.IEC61970.Core.ConductingEquipment ConductingEquipment;

		public BaseVoltage(){

		}

		~BaseVoltage(){

		}

	}//end BaseVoltage

}//end namespace Core