///////////////////////////////////////////////////////////
//  ConductingEquipment.cs
//  Implementation of the Class ConductingEquipment
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:41 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// The parts of the power system that are designed to carry current or that are
	/// conductively connected through terminals.
	/// </summary>
	public class ConductingEquipment : Equipment {

		public ConductingEquipment(){

		}

		~ConductingEquipment(){

		}

	}//end ConductingEquipment

}//end namespace Core