///////////////////////////////////////////////////////////
//  ConnectivityNodeContainer.cs
//  Implementation of the Class ConnectivityNodeContainer
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:51 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A base class for all objects that may contain connectivity nodes or topological
	/// nodes.
	/// </summary>
	public class ConnectivityNodeContainer : PowerSystemResource {

		public ConnectivityNodeContainer(){

		}

		~ConnectivityNodeContainer(){

		}

	}//end ConnectivityNodeContainer

}//end namespace Core