///////////////////////////////////////////////////////////
//  Equipment.cs
//  Implementation of the Class Equipment
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:39 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// The parts of a power system that are physical devices, electronic or mechanical.
	/// 
	/// </summary>
	public class Equipment : PowerSystemResource {

		public Equipment(){

		}

		~Equipment(){

		}

	}//end Equipment

}//end namespace Core