///////////////////////////////////////////////////////////
//  EquipmentContainer.cs
//  Implementation of the Class EquipmentContainer
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:53 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A modeling construct to provide a root class for containing equipment.
	/// </summary>
	public class EquipmentContainer : ConnectivityNodeContainer {

		/// <summary>
		/// Contained equipment.
		/// </summary>
		public TC57CIM.IEC61970.Core.Equipment Equipments;

		public EquipmentContainer(){

		}

		~EquipmentContainer(){

		}

	}//end EquipmentContainer

}//end namespace Core