///////////////////////////////////////////////////////////
//  GeographicalRegion.cs
//  Implementation of the Class GeographicalRegion
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:54 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A geographical region of a power system network model.
	/// </summary>
	public class GeographicalRegion : IdentifiedObject {

		/// <summary>
		/// All sub-geograhpical regions within this geographical region.
		/// </summary>
		public TC57CIM.IEC61970.Core.SubGeographicalRegion Regions;

		public GeographicalRegion(){

		}

		~GeographicalRegion(){

		}

	}//end GeographicalRegion

}//end namespace Core