///////////////////////////////////////////////////////////
//  GeographicalRegion.cs
//  Implementation of the Class GeographicalRegion
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:54 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
using FTN.Common;

namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A geographical region of a power system network model.
	/// </summary>
	public class GeographicalRegion : IdentifiedObject {

        private List<long> subGeoRegions = new List<long>();

        public GeographicalRegion()
        {

        }

        public GeographicalRegion(long globalId) : base(globalId)
        {
        }

        public List<long> SubGeoRegions
        {
            get { return subGeoRegions; }
            set { subGeoRegions = value; }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if (base.Equals(obj))
            {
                GeographicalRegion x = (GeographicalRegion)obj;
                return (CompareHelper.CompareLists(x.subGeoRegions, this.subGeoRegions));
            }
            else
            {
                return false;
            }
        }

        #region IAccess implementation

        public override bool HasProperty(ModelCode t)
        {
            switch (t)
            {
                case ModelCode.GEOREGION_SUBGEOREGIONS:
                    return true;

                default:
                    return base.HasProperty(t);
            }
        }

        public override void GetProperty(Property property)
        {
            switch (property.Id)
            {
                case ModelCode.GEOREGION_SUBGEOREGIONS:
                    property.SetValue(subGeoRegions);
                    break;

                default:
                    base.GetProperty(property);
                    break;
            }
        }

        public override void SetProperty(Property property)
        {
            switch (property.Id)
            {
                default:
                    base.SetProperty(property);
                    break;
            }
        }

        #endregion IAccess implementation

        #region IReference implementation

        public override bool IsReferenced
        {
            get
            {
                return subGeoRegions.Count != 0 || base.IsReferenced;
            }
        }

        public override void GetReferences(Dictionary<ModelCode, List<long>> references, TypeOfReference refType)
        {
            if (subGeoRegions != null && subGeoRegions.Count != 0 && (refType == TypeOfReference.Target || refType == TypeOfReference.Both))
            {
                references[ModelCode.GEOREGION_SUBGEOREGIONS] = subGeoRegions.GetRange(0, subGeoRegions.Count);
            }

            base.GetReferences(references, refType);
        }

        public override void AddReference(ModelCode referenceId, long globalId)
        {
            switch (referenceId)
            {
                case ModelCode.SUBGEOREGION_GEOREG:
                    subGeoRegions.Add(globalId);
                    break;

                default:
                    base.AddReference(referenceId, globalId);
                    break;
            }
        }

        public override void RemoveReference(ModelCode referenceId, long globalId)
        {
            switch (referenceId)
            {
                case ModelCode.SUBGEOREGION_GEOREG:

                    if (subGeoRegions.Contains(globalId))
                    {
                        subGeoRegions.Remove(globalId);
                    }
                    else
                    {
                        CommonTrace.WriteTrace(CommonTrace.TraceWarning, "Entity (GID = 0x{0:x16}) doesn't contain reference 0x{1:x16}.", this.GlobalId, globalId);
                    }

                    break;

                default:
                    base.RemoveReference(referenceId, globalId);
                    break;
            }
        }

        #endregion IReference implementation

        public void RD2Class(ResourceDescription rd)
        {
            foreach(Property p in rd.Properties)
            {
                if (p.Id == ModelCode.GEOREGION_SUBGEOREGIONS)
                {
                    foreach (long l in p.PropertyValue.LongValues)
                    {
                        this.AddReference(ModelCode.SUBGEOREGION_GEOREG, l);
                    }
                }
                else
                {
                    SetProperty(p);
                }
            }
        }

    }//end GeographicalRegion

}//end namespace Core