///////////////////////////////////////////////////////////
//  IdentifiedObject.cs
//  Implementation of the Class IdentifiedObject
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:47 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Domain;
using TC57CIM.IEC61970.InfIEC61970.InfCore;
using TC57CIM.IEC61970.DiagramLayout;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// This is a root class to provide common identification for all classes needing
	/// identification and naming attributes.
	/// </summary>
	public class IdentifiedObject {

		/// <summary>
		/// Master resource identifier issued by a model authority. The mRID is globally
		/// unique within an exchange context.
		/// Global uniqeness is easily achived by using a UUID for the mRID. It is strongly
		/// recommended to do this.
		/// For CIMXML data files in RDF syntax, the mRID is mapped to rdf:ID or rdf:about
		/// attributes that identify CIM object elements.
		/// </summary>
		public TC57CIM.IEC61970.Domain.String mRID;
		/// <summary>
		/// The name is any free human readable and possibly non unique text naming the
		/// object.
		/// </summary>
		public TC57CIM.IEC61970.Domain.String name;
		/// <summary>
		/// An IdentifiedObject belongs to a Modeling Authority Set for purposes of
		/// defining a group of data maintained by the same Modeling Authority.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.InfCore.ModelingAuthoritySet ModelingAuthoritySet;
		/// <summary>
		/// The diagram objects that are associated with the domain object.
		/// </summary>
		public TC57CIM.IEC61970.DiagramLayout.DiagramObject DiagramObjects;

		public IdentifiedObject(){

		}

		~IdentifiedObject(){

		}

	}//end IdentifiedObject

}//end namespace Core