///////////////////////////////////////////////////////////
//  PowerSystemResource.cs
//  Implementation of the Class PowerSystemResource
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:49 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
using TC57CIM.IEC61970.Meas;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A power system resource can be an item of equipment such as a switch, an
	/// equipment container containing many individual items of equipment such as a
	/// substation, or an organisational entity such as sub-control area. Power system
	/// resources can have measurements associated.
	/// </summary>
	public class PowerSystemResource : IdentifiedObject {

		/// <summary>
		/// Custom classification for this power system resource.
		/// </summary>
		public TC57CIM.IEC61970.Core.PSRType PSRType;
		/// <summary>
		/// The measurements associated with this power system resource.
		/// </summary>
		public TC57CIM.IEC61970.Meas.Measurement Measurements;

		public PowerSystemResource(){

		}

		~PowerSystemResource(){

		}

	}//end PowerSystemResource

}//end namespace Core