///////////////////////////////////////////////////////////
//  PowerSystemResource.cs
//  Implementation of the Class PowerSystemResource
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:49 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
using TC57CIM.IEC61970.Meas;
using FTN.Common;

namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A power system resource can be an item of equipment such as a switch, an
	/// equipment container containing many individual items of equipment such as a
	/// substation, or an organisational entity such as sub-control area. Power system
	/// resources can have measurements associated.
	/// </summary>
	public class PowerSystemResource : IdentifiedObject {

        public PowerSystemResource(long globalId)
            : base(globalId)
        {
        }

        public override bool Equals(object obj)
        {
            if (base.Equals(obj))
            {
                PowerSystemResource x = (PowerSystemResource)obj;
                return true;
            }
            else
            {
                return false;
            }
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #region IAccess implementation

        public override bool HasProperty(ModelCode property)
        {
            switch (property)
            {
                default:
                    return base.HasProperty(property);
            }
        }

        public override void GetProperty(Property property)
        {
            switch (property.Id)
            {
                default:
                    base.GetProperty(property);
                    break;
            }
        }

        public override void SetProperty(Property property)
        {
            switch (property.Id)
            {
                default:
                    base.SetProperty(property);
                    break;
            }
        }

        #endregion IAccess implementation

	}//end PowerSystemResource

}//end namespace Core