///////////////////////////////////////////////////////////
//  SubGeographicalRegion.cs
//  Implementation of the Class SubGeographicalRegion
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:55 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
using TC57CIM.IEC61970.Wires;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A subset of a geographical region of a power system network model.
	/// </summary>
	public class SubGeographicalRegion : IdentifiedObject {

		/// <summary>
		/// The substations in this sub-geographical region.
		/// </summary>
		public TC57CIM.IEC61970.Core.Substation Substations;
		/// <summary>
		/// The lines within the sub-geographical region.
		/// </summary>
		public TC57CIM.IEC61970.Wires.Line Lines;

		public SubGeographicalRegion(){

		}

		~SubGeographicalRegion(){

		}

	}//end SubGeographicalRegion

}//end namespace Core