///////////////////////////////////////////////////////////
//  Substation.cs
//  Implementation of the Class Substation
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:16:57 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A collection of equipment for purposes other than generation or utilization,
	/// through which electric energy in bulk is passed for the purposes of switching
	/// or modifying its characteristics.
	/// </summary>
	public class Substation : EquipmentContainer {

		/// <summary>
		/// The voltage levels within this substation.
		/// </summary>
		public TC57CIM.IEC61970.Core.VoltageLevel VoltageLevels;
		/// <summary>
		/// Bays contained in the substation.
		/// </summary>
		public TC57CIM.IEC61970.Core.Bay Bays;

		public Substation(){

		}

		~Substation(){

		}

	}//end Substation

}//end namespace Core