///////////////////////////////////////////////////////////
//  VoltageLevel.cs
//  Implementation of the Class VoltageLevel
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2017 7:17:12 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TC57CIM.IEC61970.Core;
namespace TC57CIM.IEC61970.Core {
	/// <summary>
	/// A collection of equipment at one common system voltage forming a switchgear.
	/// The equipment typically consist of breakers, busbars, instrumentation, control,
	/// regulation and protection devices as well as assemblies of all these.
	/// </summary>
	public class VoltageLevel : EquipmentContainer {

		/// <summary>
		/// The bays within this voltage level.
		/// </summary>
		public TC57CIM.IEC61970.Core.Bay Bays;
		/// <summary>
		/// The base voltage used for all equipment within the voltage level.
		/// </summary>
		public TC57CIM.IEC61970.Core.BaseVoltage BaseVoltage;

		public VoltageLevel(){

		}

		~VoltageLevel(){

		}

	}//end VoltageLevel

}//end namespace Core